apiVersion: apps/v1
kind: Deployment
metadata:
 name: fe-application
spec:
 replicas: 1
 strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0  
 selector:
   matchLabels:
     app: fe-application
 template:
   metadata:
     labels:
       app: fe-application
   spec:
    containers:
    - name: fe-application
      image: docker.io/huynguyenquang116/fe_application:v12
      imagePullPolicy: Always
      ports:
      - containerPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fe-route
  namespace: huy-nguyenquang116-dev
spec:
  to:
    kind: Service
    name: fe-service
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None

---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  selector:
    app: fe-application
  ports:
    - name: http
      port: 8888
      targetPort: 8080
  type: ClusterIP
   