apiVersion: apps/v1
kind: Deployment
metadata:
 name: fe-application
spec:
 replicas: 1
 strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0  
 selector:
   matchLabels:
     app: fe-application
 template:
   metadata:
     labels:
       app: fe-application
   spec:
    containers:
    - name: fe-application
      image: docker.io/huynguyenquang116/fe_application:v12
      imagePullPolicy: Always
      ports:
      - containerPort: 8080