name: Trigger Tekton CI/CD on OpenShift

on:
  push:
    branches:
      - main

jobs:
  trigger-tekton:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tekton EventListener Webhook
        env:
          WEBHOOK_URL: http://myapp-listener-huy-nguyenquang116-dev.apps.rm1.0a51.p1.openshiftapps.com
        run: |
          curl -X POST $WEBHOOK_URL \
            -H "Content-Type: application/json" \
            -d '{
              "git_url": "https://github.com/huynguyenquangce/blog_system_fe",
              "git_revision": "${{ github.sha }}",
              "image_tag": "${{ github.sha }}"
            }'
