# name: Trigger Tekton Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   trigger-tekton:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download tkn
#         run: |
#           curl -LO https://github.com/tektoncd/cli/releases/download/v0.39.0/tkn_0.39.0_Linux_x86_64.tar.gz
#           tar -xvf tkn_0.39.0_Linux_x86_64.tar.gz
#           sudo mv tkn /usr/local/bin



