name: Trigger Tekton Pipeline

on:
  push:
    branches:
      - main

env:
  GIT_SHA: ${{ github.sha }}

jobs:
  trigger-tekton:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tekton via curl
        run: |
          curl -X POST http://myapp-listener-huy-nguyenquang116-dev.apps.rm1.0a51.p1.openshiftapps.com \
            -H "Content-Type: application/json" \
            -d "{
              \"git-url\": \"https://github.com/huynguyenquangce/fe_java_application_cicd_ocp.git\",
              \"git-revision\": \"refs/heads/main\",
              \"image-tag\": \"${GIT_SHA:0:7}\"
            }"
